<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Utilities\" />
    <Folder Include="RepoProxies\Implementations\" />
    <Folder Include="RepoProxies\Interfaces\" />
    <Folder Include="Services\Implementations\" />
    <Folder Include="Services\Interfaces\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankApp.Models\BankApp.Models.csproj" />
  </ItemGroup>
    <PropertyGroup>
		<CodeAnalysisRuleSet>SE.ruleset</CodeAnalysisRuleSet>
	</PropertyGroup>
</Project>
