<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankApp.Client.Shared\BankApp.Client.Shared.csproj" />
    <ProjectReference Include="..\BankApp.Models\BankApp.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Auth\" />
    <Folder Include="Views\Dashboard\" />
    <Folder Include="Views\Accounts\" />
    <Folder Include="Views\Loans\" />
    <Folder Include="Views\Investments\" />
    <Folder Include="Views\Profile\" />
    <Folder Include="Views\Crypto\" />
    <Folder Include="Views\Chat\" />
    <Folder Include="Views\Statistics\" />
    <Folder Include="Views\Transactions\" />
    <Folder Include="Views\Savings\" />
  </ItemGroup>

</Project>
