<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Views\Crypto\**" />
    <Compile Remove="wwwroot\NewFolder\**" />
    <Content Remove="Views\Crypto\**" />
    <Content Remove="wwwroot\NewFolder\**" />
    <EmbeddedResource Remove="Views\Crypto\**" />
    <EmbeddedResource Remove="wwwroot\NewFolder\**" />
    <None Remove="Views\Crypto\**" />
    <None Remove="wwwroot\NewFolder\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="appsettings.Development.json" />
    <Content Remove="appsettings.json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankApp.Client.Shared\BankApp.Client.Shared.csproj" />
    <ProjectReference Include="..\BankApp.Models\BankApp.Models.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Views\Accounts\" />
    <Folder Include="Views\Loans\" />
    <Folder Include="Views\Profile\" />
    <Folder Include="Views\Investments\" />
    <Folder Include="Views\Statistics\" />
    <Folder Include="Views\Transactions\" />
    <Folder Include="Views\Savings\" />
  </ItemGroup>

</Project>
